name: QA New Commit

on:
  push:
    branches: [ qa ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          rfbrowser init

      - name: Running Web Server
        run: |
          python -m http.server 5050 --directory ./web &

      - name: Run Robot Framework tests
        run: |
          robotcode run ./tests/suites/

      # - name: Run Robot Framework tests
      #   run: |
      #     mkdir -p results
      #     robot --outputdir results tests/

      # - name: Upload results as artifact (backup)
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: robot-results
      #     path: results/

      # - name: Deploy results to GitHub Pages
      #   uses: peaceiris/actions-gh-pages@v4
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     publish_dir: ./   # publish seluruh repo
      #     destination_dir: . # akar GitHub Pages
