name: QA Pull Request

on:
  push:
    # branches: [ qa ]
  pull_request:
    branches: [ qa ]
    # paths: ["**"]
    # paths:
    #   - "web/**"
    #   - "tests/suites/**"

jobs:
  test:
    if: github.head_ref == 'dev'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          rfbrowser init

      - name: Run Web Server
        run: |
          python -m http.server 5050 --directory ./web &

      - name: Run Robot Framework tests
        run: |
          robotcode run ./tests/suites/

      - name: Prepare files for GitHub Pages
        run: |
          mkdir -p public
          cp -r web/* public/
          mkdir -p public/results
          cp -r tests/results/* public/results/

      - name: Deploy 🚀
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
